-- Define your visual elements here
-- For examples, and a complete list on the possible elements and their
-- properties, go to https://github.com/fisadev/conky-draw/
-- (and be sure to use the lastest version)

elements = {

{

    kind = 'ring_graph',
    center = {x = 150, y = 150},
    conky_value = 'cpu cpu1',
    radius = 140,
    graduated = true,
    thickness = 40,
    number_graduation=50,
    angle_between_graduation=1,
    start_angle = 270,
    end_angle = 0,
    color= 0xFF6600,
    bar_thickness = 20,
    background_thickness = 20,
    bar_color = 0xC0C0C0,
    background_color= 0x708090,
 },{

    kind = 'ring_graph',
    center = {x = 150, y = 150},
    conky_value = 'cpu cpu2',
    radius = 115,
    graduated = true,
    thickness = 40,
    number_graduation=50,
    angle_between_graduation=1,
    start_angle = 270,
    end_angle = 0,
    color= 0xFF6600,
    bar_thickness = 20,
    background_thickness = 20,
    bar_color = 0xC0C0C0,
    background_color= 0x708090,
 },
 {
     kind = 'ring_graph',
     center = {x = 150, y = 150},
     conky_value = 'cpu cpu3',
     radius = 90,
     graduated = true,
     thickness = 40,
     number_graduation=50,
     angle_between_graduation=1,
     start_angle = 270,
     end_angle = 0,
     color= 0xFF6600,
     bar_thickness = 20,
     background_thickness = 20,
     bar_color = 0xC0C0C0,
     background_color= 0x708090,
  },
  {
      kind = 'ring_graph',
      center = {x = 150, y = 150},
      conky_value = 'cpu cpu4',
      radius = 65,
      graduated = true,
      thickness = 40,
      number_graduation=50,
      angle_between_graduation=1,
      start_angle = 270,
      end_angle = 0,
      color= 0xFF6600,
      bar_thickness = 20,
      background_thickness = 20,
      bar_color = 0xC0C0C0,
      background_color= 0x708090,
   },

   {
       kind = 'ring_graph',
       center = {x = 150, y = 500},
       conky_value = 'memperc',
       radius = 140,
       graduated = true,
       thickness = 40,
       number_graduation=50,
       angle_between_graduation=1,
       start_angle = 270,
       end_angle = 0,
       color= 0xFF6600,
       bar_thickness = 20,
       background_thickness = 20,
       bar_color = 0xC0C0C0,

       background_color= 0x708090,
    },
    {
        kind = 'ring_graph',
        center = {x = 150, y = 500},
        conky_value = 'battery_percent BAT0',
        radius = 115,
        graduated = true,
        thickness = 40,
        number_graduation=50,
        angle_between_graduation=1,
        start_angle = 270,
        end_angle = 0,
        color= 0x990000,
        bar_thickness = 20,
        background_thickness = 20,
        bar_color = 0x990000,
        critical_threshold = 40,
        bar_alpha_critical = 0xC0C0C0,
        background_alpha_critical = 0xC0C0C0,
        background_color_critical = 0xC0C0C0,
        bar_color_critical = 0xC0C0C0,
        background_color= 0x708090,
     },

}
